# https://taskfile.dev

version: '3'

tasks:
  init:
    desc: Install dependencies
    cmds:
      - pnpm install
  lint:
    desc: Run linter
    cmds:
      - pnpm run lint:all
  fmt:
    desc: Run formatter
    cmds:
      - pnpm run format:all
  dev:
    desc: Run Desktop development
    cmds:
      - pnpm run tauri dev
  dev-android:
    desc: Run Android development
    cmds:
      - pnpm tauri android dev
  build-windows:
    desc: Build Windows Apps
    cmds:
      - pnpm run tauri:build
